// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9yrvpaguYhHzO-2nZ8FoWbyOBGUXYL-4',
    appId: '1:868711440893:web:3d37406015ec5bc9a07994',
    messagingSenderId: '868711440893',
    projectId: 'yatri-fly',
    authDomain: 'yatri-fly.firebaseapp.com',
    storageBucket: 'yatri-fly.firebasestorage.app',
    measurementId: 'G-HYBG1LGEL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByS-RH997k_eI0E6I5S1k_p97c5Zhe-Tw',
    appId: '1:70246719949:android:b5bb8f7c5ef10fa170e484',
    messagingSenderId: '70246719949',
    projectId: 'lekhan-ai-bc906',
    storageBucket: 'lekhan-ai-bc906.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq_-Bzs_bFlfyKoLCY_GMfJCgfA5_OzE0',
    appId: '1:70246719949:ios:efc4ed3aac542be370e484',
    messagingSenderId: '70246719949',
    projectId: 'lekhan-ai-bc906',
    storageBucket: 'lekhan-ai-bc906.firebasestorage.app',
    iosBundleId: 'com.example.lekkhanAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxBMbJyuxPKfpGwgYt-AAGgsGZMrsq9JM',
    appId: '1:868711440893:ios:69c095c3b000e0daa07994',
    messagingSenderId: '868711440893',
    projectId: 'yatri-fly',
    storageBucket: 'yatri-fly.firebasestorage.app',
    iosBundleId: 'com.example.yatriFly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9yrvpaguYhHzO-2nZ8FoWbyOBGUXYL-4',
    appId: '1:868711440893:web:f2fea493b1b8b370a07994',
    messagingSenderId: '868711440893',
    projectId: 'yatri-fly',
    authDomain: 'yatri-fly.firebaseapp.com',
    storageBucket: 'yatri-fly.firebasestorage.app',
    measurementId: 'G-EMB7SKNYTV',
  );

}